import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

// import { dark } from "@clerk/themes";
import { ClerkProvider } from "@clerk/nextjs";
import { zhCN } from "@clerk/localizations";
import QueryClientProviderApp from "@/app/components/QueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProviderApp>
      <ClerkProvider
        localization={zhCN}
        appearance={{
          baseTheme: [],
        }}
      >
        <html lang="en" suppressHydrationWarning>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex-row`}
          >
            <ThemeProvider attribute="data-mode">
              <div className="w-screen h-screen">
                <div className="">{children}</div>
              </div>
            </ThemeProvider>
          </body>
        </html>
      </ClerkProvider>
    </QueryClientProviderApp>
  );
}
